spring:
  application:
    name: leavemanagementsystem
  datasource:
    url: jdbc:mysql://localhost:3306/lms_schema?useSSL=false
    username: newuser2
    password: anits123*
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9999

